// Copyright 2022 Mike Helmick
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Turns the Go package's word lists into a TypeScript module.
//
// pkg/wordle/words.go and answers.go stay the single source of truth for both
// implementations; this script is the only thing that copies them. Reading Go
// source rather than a data file is deliberate: the lists live inline in the
// package, and keeping a parallel text copy purely to feed this script would
// mean two copies of the same data, free to drift. The output is committed so
// builds and deploys are hermetic, and CI runs `--check` to fail if the two
// ever fall out of step.
//
//   node scripts/gen-words.mjs           # write src/data/words.ts
//   node scripts/gen-words.mjs --check   # exit 1 if the file is stale

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(HERE, '../../pkg/wordle/words.go');
const ANSWERS = resolve(HERE, '../../pkg/wordle/answers.go');
const TARGET = resolve(HERE, '../src/data/words.ts');

const WORD_LENGTH = 5;
// Words per line in the packed literal. Keeps the generated file reviewable
// instead of one 64k-character line.
const WORDS_PER_LINE = 40;

// Pulls the quoted five-letter literals out of a Go slice declaration. The
// source files are flat lists of string literals with nothing else quoted in
// them, so a scan for quoted words is sufficient and stays readable.
function parseWordList(raw, source) {
  const body = raw.slice(raw.indexOf('[]string{'));
  const words = [];
  const seen = new Set();
  for (const [, word] of body.matchAll(/"([^"]*)"/g)) {
    if (!/^[A-Z]{5}$/.test(word)) {
      throw new Error(`${source}: ${JSON.stringify(word)} is not five uppercase letters`);
    }
    if (seen.has(word)) continue;
    seen.add(word);
    words.push(word);
  }
  if (words.length === 0) throw new Error(`${source}: no words found`);
  words.sort();
  return words;
}

function pack(words) {
  const chunks = [];
  for (let i = 0; i < words.length; i += WORDS_PER_LINE) {
    chunks.push(`  '${words.slice(i, i + WORDS_PER_LINE).join('')}',`);
  }
  return chunks.join('\n');
}

function render(words, answers) {
  const chunks = pack(words);
  const answerChunks = pack(answers);

  return `// Code generated by scripts/gen-words.mjs. DO NOT EDIT.
//
// Sources: pkg/wordle/words.go and pkg/wordle/answers.go -- the same lists the
// Go solver compiles in.
// Regenerate with: npm run gen:words

/** Number of letters in every word. */
export const WORD_LENGTH = ${WORD_LENGTH};

/** Number of words in the list. */
export const WORD_COUNT = ${words.length};

// Stored as one packed string rather than an array of ${words.length} quoted
// literals: same data, roughly a third of the bytes over the wire.
const PACKED = [
${chunks}
].join('');

const PACKED_ANSWERS = [
${answerChunks}
].join('');

/** Every allowed guess, uppercase and sorted. */
export const WORDS: readonly string[] = (() => {
  const out: string[] = new Array(WORD_COUNT);
  for (let i = 0; i < WORD_COUNT; i++) {
    out[i] = PACKED.slice(i * WORD_LENGTH, (i + 1) * WORD_LENGTH);
  }
  return out;
})();

/**
 * The same words as letter indices 0-25, laid out end to end: word \`i\`
 * occupies \`[i * WORD_LENGTH, (i + 1) * WORD_LENGTH)\`.
 *
 * Scoring every guess against every candidate touches this a few million times
 * per ranking pass, and a flat typed array avoids re-deriving char codes in the
 * inner loop.
 */
export const PACKED_LETTERS: Uint8Array = (() => {
  const out = new Uint8Array(WORD_COUNT * WORD_LENGTH);
  for (let i = 0; i < out.length; i++) {
    out[i] = PACKED.charCodeAt(i) - 65;
  }
  return out;
})();

/** Number of words that have ever been a solution. */
export const ANSWER_COUNT = ${answers.length};

/**
 * The words that have ever been a solution.
 *
 * Only about one legal guess in six. The rest exist so the game accepts them as
 * input: LOAST and PLAST are perfectly legal to type but will never be the
 * answer. They are ranked below these rather than filtered out, because the
 * puzzle's answers are editorially chosen now rather than drawn from a fixed
 * list, so a word outside this set can still turn up.
 */
export const ANSWERS: ReadonlySet<string> = new Set(
  Array.from({ length: ANSWER_COUNT }, (_, i) =>
    PACKED_ANSWERS.slice(i * WORD_LENGTH, (i + 1) * WORD_LENGTH),
  ),
);

/** Whether \`WORDS[i]\` has ever been a solution, for index-based hot paths. */
export const IS_ANSWER: Uint8Array = (() => {
  const out = new Uint8Array(WORD_COUNT);
  for (let i = 0; i < WORD_COUNT; i++) {
    out[i] = ANSWERS.has(WORDS[i] as string) ? 1 : 0;
  }
  return out;
})();
`;
}

const words = parseWordList(readFileSync(SOURCE, 'utf8'), SOURCE);
const answers = parseWordList(readFileSync(ANSWERS, 'utf8'), ANSWERS);

// An answer that is not a legal guess would mean the two lists have drifted,
// and every ranking built on them would be quietly wrong.
const legal = new Set(words);
for (const answer of answers) {
  if (!legal.has(answer)) {
    throw new Error(`${ANSWERS}: ${JSON.stringify(answer)} is not present in ${SOURCE}`);
  }
}

const rendered = render(words, answers);
const check = process.argv.includes('--check');

if (check) {
  let current = '';
  try {
    current = readFileSync(TARGET, 'utf8');
  } catch {
    console.error(`${TARGET} is missing. Run: npm run gen:words`);
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(`${TARGET} is out of date with the Go word lists. Run: npm run gen:words`);
    process.exit(1);
  }
  console.log(`src/data/words.ts is up to date (${words.length} words, ${answers.length} answers).`);
} else {
  writeFileSync(TARGET, rendered);
  console.log(`Wrote src/data/words.ts (${words.length} words, ${answers.length} answers).`);
}
