// Copyright 2022 Mike Helmick
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Turns the Go package's embedded word list into a TypeScript module.
//
// pkg/wordle/words5.txt stays the single source of truth for both
// implementations; this script is the only thing that copies it. The output is
// committed so builds and deploys are hermetic, and CI runs `--check` to fail
// if the two ever fall out of step.
//
//   node scripts/gen-words.mjs           # write src/data/words.ts
//   node scripts/gen-words.mjs --check   # exit 1 if the file is stale

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(HERE, '../../pkg/wordle/words5.txt');
const TARGET = resolve(HERE, '../src/data/words.ts');

const WORD_LENGTH = 5;
// Words per line in the packed literal. Keeps the generated file reviewable
// instead of one 64k-character line.
const WORDS_PER_LINE = 40;

function parseWordList(raw) {
  const words = [];
  const seen = new Set();
  // The source ships with CRLF endings and a trailing newline.
  const lines = raw.split('\n');
  for (const [i, line] of lines.entries()) {
    const word = line.trim().toUpperCase();
    if (word === '') continue;
    if (!/^[A-Z]{5}$/.test(word)) {
      throw new Error(`${SOURCE} line ${i + 1}: ${JSON.stringify(word)} is not five uppercase letters`);
    }
    if (seen.has(word)) continue;
    seen.add(word);
    words.push(word);
  }
  words.sort();
  return words;
}

function render(words) {
  const chunks = [];
  for (let i = 0; i < words.length; i += WORDS_PER_LINE) {
    chunks.push(`  '${words.slice(i, i + WORDS_PER_LINE).join('')}',`);
  }

  return `// Code generated by scripts/gen-words.mjs. DO NOT EDIT.
//
// Source: pkg/wordle/words5.txt -- the same list the Go solver embeds.
// Regenerate with: npm run gen:words

/** Number of letters in every word. */
export const WORD_LENGTH = ${WORD_LENGTH};

/** Number of words in the list. */
export const WORD_COUNT = ${words.length};

// Stored as one packed string rather than an array of ${words.length} quoted
// literals: same data, roughly a third of the bytes over the wire.
const PACKED = [
${chunks.join('\n')}
].join('');

/** Every allowed guess, uppercase and sorted. */
export const WORDS: readonly string[] = (() => {
  const out: string[] = new Array(WORD_COUNT);
  for (let i = 0; i < WORD_COUNT; i++) {
    out[i] = PACKED.slice(i * WORD_LENGTH, (i + 1) * WORD_LENGTH);
  }
  return out;
})();

/**
 * The same words as letter indices 0-25, laid out end to end: word \`i\`
 * occupies \`[i * WORD_LENGTH, (i + 1) * WORD_LENGTH)\`.
 *
 * Scoring every guess against every candidate touches this a few million times
 * per ranking pass, and a flat typed array avoids re-deriving char codes in the
 * inner loop.
 */
export const PACKED_LETTERS: Uint8Array = (() => {
  const out = new Uint8Array(WORD_COUNT * WORD_LENGTH);
  for (let i = 0; i < out.length; i++) {
    out[i] = PACKED.charCodeAt(i) - 65;
  }
  return out;
})();
`;
}

const words = parseWordList(readFileSync(SOURCE, 'utf8'));
const rendered = render(words);
const check = process.argv.includes('--check');

if (check) {
  let current = '';
  try {
    current = readFileSync(TARGET, 'utf8');
  } catch {
    console.error(`${TARGET} is missing. Run: npm run gen:words`);
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(`${TARGET} is out of date with pkg/wordle/words5.txt. Run: npm run gen:words`);
    process.exit(1);
  }
  console.log(`src/data/words.ts is up to date (${words.length} words).`);
} else {
  writeFileSync(TARGET, rendered);
  console.log(`Wrote src/data/words.ts (${words.length} words).`);
}
